//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeApp.Models.EmployeeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Salary { get; set; }
    
        public virtual City City { get; set; }
    }
}
